Add routes config for json-server
nss-day-cohort-29/c29-heroku-test pull request #6
Opened 2019-04-20 00:07 UTC by AdamSheaffer

# The problem this solves
json-server, when in **PROD**, is serving both the static files _and_ the database; so when a user enters the site at a certain route (i.e. `/posts`), we have to give our best guess as to whether the path they are requesting is a DB resource or one registered with the react router. This change passes a flag to `json-server` that puts all DB routes at the `/api/` path. This eliminates the need for `server.js` but does add a simple middleware that checks if the request is for an api route. If it's not, return `index.html`

For the sake of the `start:dev` script, I also installed `concurrently` so you can run your json server and react server with one command.

2019-04-21 22:15 UTC, askingalot requested changes

2019-04-21 22:15 UTC, askingalot commented on package.json
> +    "concurrently": "^4.1.0",
Nice touch. I like this a lot. I can't tell you how many times a student has come to me for help only to find out they didn't start json-server.

2019-04-21 22:15 UTC, askingalot commented on API/middleware.js
> +const path = require('path');
I don't understand how this middleware works. It looks like it'll always return the `index.html` unless the requested url contains '/api/`. How does it hand off to json-server to server static files?

Now that I think about it, given what you said (and what I read) about the way the "routes" feature works, I'm surprised we even need this middleware.

2019-04-22 15:36 UTC, AdamSheaffer commented
@askingalot, I made changes to the npm scripts to remove the watch flag in prod. Waiting for a real trial run deploying to heroku to see if there is any issue with specifying the port

2019-05-05 17:51 UTC, merged